import type { DriveSnapshot } from '../types';
import { daysAgo } from './format';

export const demoSnapshot: DriveSnapshot = {
  displayName: 'Nguyễn An',
  email: 'ban@example.com',
  incompleteSearch: false,
  quota: {
    limit: '15000000000',
    usage: '12180000000',
    usageInDrive: '10120000000',
    usageInDriveTrash: '680000000',
  },
  files: [
    {
      id: 'demo-1',
      name: 'Video du lịch Đà Lạt.mov',
      mimeType: 'video/quicktime',
      size: '2860000000',
      quotaBytesUsed: '2860000000',
      md5Checksum: 'video-dalat-copy',
      modifiedTime: daysAgo(822),
      viewedByMeTime: daysAgo(728),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-2',
      name: 'Video du lịch Đà Lạt - copy.mov',
      mimeType: 'video/quicktime',
      size: '2860000000',
      quotaBytesUsed: '2860000000',
      md5Checksum: 'video-dalat-copy',
      modifiedTime: daysAgo(788),
      viewedByMeTime: daysAgo(701),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-3',
      name: 'Archive thiết kế 2022.zip',
      mimeType: 'application/zip',
      size: '1420000000',
      quotaBytesUsed: '1420000000',
      md5Checksum: 'archive-2022',
      modifiedTime: daysAgo(1160),
      viewedByMeTime: daysAgo(1118),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-4',
      name: 'Bản ghi cuộc họp.mp4',
      mimeType: 'video/mp4',
      size: '920000000',
      quotaBytesUsed: '920000000',
      md5Checksum: 'meeting-recording',
      modifiedTime: daysAgo(94),
      viewedByMeTime: daysAgo(90),
      ownedByMe: true,
      starred: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-5',
      name: 'Bộ ảnh sản phẩm RAW',
      mimeType: 'application/vnd.google-apps.folder',
      modifiedTime: daysAgo(755),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-6',
      name: 'Kế hoạch quý 4',
      mimeType: 'application/vnd.google-apps.document',
      quotaBytesUsed: '248000',
      modifiedTime: daysAgo(7),
      viewedByMeTime: daysAgo(1),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-7',
      name: 'Brand assets cũ.psd',
      mimeType: 'image/vnd.adobe.photoshop',
      size: '768000000',
      quotaBytesUsed: '768000000',
      md5Checksum: 'old-brand-assets',
      modifiedTime: daysAgo(913),
      viewedByMeTime: daysAgo(890),
      ownedByMe: true,
      capabilities: { canTrash: true },
    },
    {
      id: 'demo-8',
      name: 'Tài liệu được chia sẻ.pdf',
      mimeType: 'application/pdf',
      size: '640000000',
      quotaBytesUsed: '0',
      md5Checksum: 'shared-file',
      modifiedTime: daysAgo(1000),
      ownedByMe: false,
      capabilities: { canTrash: false },
    },
  ],
};
